export enum ColorSlug {
  Black = 'black',
  Gold = 'gold',
  Yellow = 'yellow',
  Green = 'green',
  MidnightGreen = 'midnightgreen',
  Silver = 'silver',
  SpaceGray = 'spacegray',
  SpaceGrayDash = 'space-gray',
  SpaceGrayAlt = 'space gray',
  Red = 'red',
  White = 'white',
  Purple = 'purple',
  Coral = 'coral',
  RoseGold = 'rosegold',
  Midnight = 'midnight',
  SpaceBlack = 'spaceblack',
  Blue = 'blue',
  Pink = 'pink',
  SierraBlue = 'sierrablue',
  Graphite = 'graphite',
  SkyBlue = 'sky-blue',
  Starlight = 'starlight',
}

export const SLUG_TO_CSS_COLOR: Record<string, string> = {
  [ColorSlug.Black]: '#000000',
  [ColorSlug.Gold]: '#D4AF37',
  [ColorSlug.Yellow]: '#FFEB3B',
  [ColorSlug.Green]: '#4CAF50',
  [ColorSlug.MidnightGreen]: '#004D40',
  [ColorSlug.Silver]: '#C0C0C0',
  [ColorSlug.SpaceGray]: '#6E6E6E',
  [ColorSlug.SpaceGrayDash]: '#6E6E6E',
  [ColorSlug.SpaceGrayAlt]: '#6E6E6E',
  [ColorSlug.Red]: '#F44336',
  [ColorSlug.White]: '#FFFFFF',
  [ColorSlug.Purple]: '#9C27B0',
  [ColorSlug.Coral]: '#FF7F50',
  [ColorSlug.RoseGold]: '#B76E79',
  [ColorSlug.Midnight]: '#1A1A2E',
  [ColorSlug.SpaceBlack]: '#2E2E2E',
  [ColorSlug.Blue]: '#2196F3',
  [ColorSlug.Pink]: '#E91E63',
  [ColorSlug.SierraBlue]: '#0066CC',
  [ColorSlug.Graphite]: '#444444',
  [ColorSlug.SkyBlue]: '#87CEEB',
  [ColorSlug.Starlight]: '#F0E68C',
};
